component_depth: 1
languages:
- name: php

exclude:
  - /bootstrap/.*
  - /config/.*
  - /database/.*
  - /public/.*
  - /resources/.*
  - /routes/.*
  - /storage/.*
  - /app/Services/Forus/Notification/.*
  - /app/Mail/Funds/.*

  
  
