component_depth: 1
languages:
- name: php
  production:
    exclude:
      - /bootstrap/.*
      - /config/.*
      - /database/.*
      - /public/.*
      - /resources/.*
      - /routes/.*
      - /storage/.*    
  test:
    include:
      - /tests/.*
