component_depth: 1
languages:
- name: php
  production:
    exclude:
      - /app/.*
      - /routes/api-platform.php
      - /database/.*
      
  test:
    include:
      - /app/.*
    exclude:
      - /app/Http/.*
      - /app/Services/.*
