component_depth: 1
languages:
- name: php

exclude:
  - /bootstrap/.*
  - /config/.*
  - /database/.*
  - /public/.*
  - /resources/.*
  - /routes/.*
  - /storage/.*
  - /app/Mail/Funds/.*
  - /app/Mail/Forus/.*
  - /app/Mail/Vouchers/.*
  - /app/Services/Forus/Notification/.*
  - /app/Http/Controllers/Api/Platform/.*
  - /app/Policies/FundRequestClarificationPolicy.php
  - /app/Http/Controllers/Api/IdentityController.php
  - /app/Http/Controllers/Api/IdentityFallbackController.php
  
